disabled_rules:
  - trailing_whitespace
  - todo
  - multiple_closures_with_trailing_closure

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - explicit_init
  - explicit_type_interface
  - first_where
  - overridden_super_call
  - redundant_nil_coalescing
  - vertical_whitespace_closing_braces
  - weak_delegate

line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

large_tuple:
  warning: 3
  error: 4

custom_rules:
  - CanopyRules

excluded:
  - Carthage
  - Pods
  - Canopy.xcodeproj
  - .build

included:
  - Canopy
  - Sources
  - Examples
  - Tests
